import os
import json
import datetime
import smtplib
import requests
import gspread
import openai
from google.oauth2.service_account import Credentials
from google.oauth2.credentials import Credentials as UserCredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from yt_dlp import YoutubeDL
from moviepy.editor import VideoFileClip, AudioFileClip, TextClip, CompositeVideoClip, vfx, afx
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# --- 환경 변수 로드 ---
GCP_SA_KEY = json.loads(os.environ['GCP_SA_KEY'])
SHEET_URL = os.environ['SHEET_URL']
OPENAI_API_KEY = os.environ['OPENAI_API_KEY']
YT_CLIENT_ID = os.environ['YOUTUBE_CLIENT_ID']
YT_CLIENT_SECRET = os.environ['YOUTUBE_CLIENT_SECRET']
YT_REFRESH_TOKEN = os.environ['YOUTUBE_REFRESH_TOKEN']
EMAIL_USER = os.environ['EMAIL_USER']
EMAIL_PASS = os.environ['EMAIL_PASS']

openai.api_key = OPENAI_API_KEY

def send_email(subject, body):
    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_USER
        msg['To'] = EMAIL_USER
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(EMAIL_USER, EMAIL_PASS)
        server.sendmail(EMAIL_USER, EMAIL_USER, msg.as_string())
        server.quit()
        print("이메일 발송 성공")
    except Exception as e:
        print(f"이메일 발송 실패: {e}")

def get_target_link():
    print("스프레드시트 확인 중...")
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds = Credentials.from_service_account_info(GCP_SA_KEY, scopes=scope)
    client = gspread.authorize(creds)
    sheet = client.open_by_url(SHEET_URL).sheet1
    data = sheet.get_all_records()
    
    today = datetime.datetime.now().strftime("%Y-%m-%d")
    print(f"오늘 날짜: {today}")
    
    for row in data:
        # 날짜 형식이 다양할 수 있으니 문자열 포함 여부로 체크
        if today in str(row.get('날짜', '')) or today in str(row.get('Date', '')):
            return row.get('링크', '') or row.get('Link', '')
    return None

def download_video(url):
    print(f"영상 다운로드 시작: {url}")
    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
        'outtmpl': 'input_video.%(ext)s',
        'noplaylist': True,
    }
    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        return "input_video.mp4", info.get('title', 'Unknown Title')

def create_lofi_content(input_path):
    print("Lofi 스타일 변환 및 자막 생성 시작...")
    
    # 1. 비디오/오디오 로드
    clip = VideoFileClip(input_path)
    # 영상이 너무 길면 5분으로 자름
    if clip.duration > 300:
        clip = clip.subclip(0, 300)
        
    # 2. 오디오 Lofi 효과 (Slow & Reverb 느낌)
    # 속도를 0.85배로 줄여서 피치를 낮추고 늘어지는 느낌을 줌
    new_audio = clip.audio.fx(vfx.speedx, 0.85)
    # 볼륨을 약간 줄임
    new_audio = new_audio.volumex(0.8)
    
    # 3. 비디오 효과 (빈티지 느낌)
    # 속도를 오디오에 맞춰 0.85배로 줄임
    new_clip = clip.fx(vfx.speedx, 0.85)
    # 채도를 낮춰서(0.6) 빈티지하게
    new_clip = new_clip.fx(vfx.colorx, 0.8)
    # 약간 어둡게
    new_clip = new_clip.fx(vfx.lum_contrast, lum=-10, contrast=0.1)
    
    new_clip = new_clip.set_audio(new_audio)

    # 4. OpenAI Whisper로 자막 생성 (음성 추출 -> 텍스트)
    new_audio.write_audiofile("temp_audio.mp3")
    print("OpenAI Whisper로 자막 추출 중...")
    audio_file = open("temp_audio.mp3", "rb")
    transcript = openai.Audio.transcribe("whisper-1", audio_file)
    text_content = transcript["text"]
    
    # 자막이 너무 길면 앞부분만 잘라서 요약 형태로 하단에 표시 (디자인 단순화)
    # 전체 자막 싱크를 맞추는 건 매우 복잡하므로, 'Lofi Mood' 텍스트와 추출된 핵심 문구 일부를 띄움
    display_text = "Lofi Remixed by AI\n" + text_content[:50] + "..."
    
    # 한글 폰트가 없어서 깨질 수 있으므로 영문으로 변환하거나 시스템 폰트 사용 시도.
    # 안전하게 영문 기본 텍스트와 이모지 사용 권장. 
    # 여기서는 단순화를 위해 영문 고정 텍스트 예시 (한글 폰트 설치는 복잡함)
    txt_clip = TextClip("Relaxing Vibes\nGenerated by AI", fontsize=50, color='white', font='DejaVu-Sans-Bold')
    txt_clip = txt_clip.set_pos(('center', 'bottom')).set_duration(new_clip.duration)
    
    final_video = CompositeVideoClip([new_clip, txt_clip])
    output_filename = "output_lofi.mp4"
    final_video.write_videofile(output_filename, codec='libx264', audio_codec='aac')
    
    return output_filename

def upload_to_youtube(file_path, title):
    print("유튜브 업로드 시작...")
    creds = UserCredentials(
        None,
        refresh_token=YT_REFRESH_TOKEN,
        client_id=YT_CLIENT_ID,
        client_secret=YT_CLIENT_SECRET,
        token_uri="https://oauth2.googleapis.com/token"
    )
    
    youtube = build('youtube', 'v3', credentials=creds)
    
    request_body = {
        'snippet': {
            'title': f"[Lofi Remix] {title}",
            'description': 'This video involves AI-generated editing. Relax and Enjoy.',
            'tags': ['lofi', 'remix', 'ai'],
            'categoryId': '10' # Music
        },
        'status': {
            'privacyStatus': 'public', # 바로 공개 (테스트 시 private 권장)
            'selfDeclaredMadeForKids': False,
        }
    }
    
    media = MediaFileUpload(file_path, chunksize=-1, resumable=True)
    request = youtube.videos().insert(part="snippet,status", body=request_body, media_body=media)
    response = request.execute()
    print(f"업로드 완료! Video ID: {response.get('id')}")
    return response.get('id')

if __name__ == "__main__":
    try:
        url = get_target_link()
        if url:
            print(f"타겟 URL 발견: {url}")
            video_file, original_title = download_video(url)
            final_video = create_lofi_content(video_file)
            vid_id = upload_to_youtube(final_video, original_title)
            send_email(
                "[성공] AI Lofi 영상 업로드 완료", 
                f"원본: {original_title}\n유튜브 링크: https://youtu.be/{vid_id}"
            )
        else:
            print("오늘 날짜의 영상 링크가 없습니다.")
    except Exception as e:
        print(f"에러 발생: {e}")
        send_email("[실패] 영상 생성 중 에러 발생", str(e))
        exit(1) # GitHub Actions 실패 처리
